name: rus_tili_1_back
description: A sample command-line application.
version: 1.0.2
repository: https://github.com/Mansur5835/rus_tili_1_backend

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  jaguar: ^3.1.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
 